apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  labels:
    app: postgresql
    app.kubernetes.io/part-of: positive-thoughts
type: Opaque
stringData:
  POSTGRESQL_USER: thoughts
  POSTGRESQL_PASSWORD: thoughts
  POSTGRESQL_DATABASE: thoughts_db
